spring.application.name=nutri

api.version=v1

app.database.host=${DB_HOST:192.168.1.100}
spring.datasource.url=jdbc:sqlserver://${DB_HOST:192.168.1.100}:${DB_PORT:1433};databaseName=NutriSalud;encrypt=true;trustServerCertificate=true
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:nutri}

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.jpa.properties.hibernate.scan=com.nutriSalud.nutri.models
