spring.application.name=nutri

spring.datasource.url=jdbc:sqlserver://${DB_HOST:localhost}:${DB_PORT:1433};databaseName=NutriSalud;encrypt=true;trustServerCertificate=true
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:nutri}

# Driver SQL Server
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# CONFIGURACION JPA / HIBERNATE
# update = crea/actualiza tablas automaticamente segun tus entidades
# create = borra y recrea tablas en cada inicio (solo para desarrollo)
# validate = solo valida que las tablas coincidan con las entidades (produccion)
spring.jpa.hibernate.ddl-auto=update

# Mostrar consultas SQL en consola (desarrollo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto para SQL Server
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Escaneo de entidades JPA
spring.jpa.properties.hibernate.scan=com.nutriSalud.nutri.models
